### ISSUE TITLE
Posts are not displayed after I created them

### ISSUE THREAD

**Issue by nikolasburk** [graphcool-examples/angular-apollo-instagram-example#22]
They have been created in the Graphcool backend which I saw in a Playground

**Comment by nikolasburk** [comment]
Just noticed I have to refresh the page to make them appear 😇 maybe an info about that should also be included in the README

**Comment by marktani** [comment]
Closing in favor of #5, @kamilkisiela do you know if `updatedQueries` works reliably now?
